### ISSUE TITLE
(Possibly) Not working in Laravel 5.8

### ISSUE THREAD

**Issue by gitllermopalafox** [imanghafoori1/laravel-widgetize#54]
Hi, thanks for you work!

I'm trying to use the package in laravel 5.8 but I'm getting this error:

```
Too few arguments to function Imanghafoori\Widgets\Utils\WidgetRenderer::renderWidget(), 0 passed in /demo-widgetize/storage/framework/views/c718b25c60e88180b3786536bce9b5328dddd1d3.php on line 6
```

I uploaded a demo project:

https://github.com/gitllermopalafox/demo-widgetize

Thanks in advance.

**Comment by imanghafoori1** [comment]
@gitllermopalafox Thanks for reporting the issue.
The package can work in production with L5.8
The error you see is because the default view which is generated by artisan is somewhat faulty.

I have used this package in a laravel 5.8 project and it worked for me.

Anyway I try to have a better error message for this kind of situation in the next patch release.

checkout the v1.9.20 version

**Comment by gitllermopalafox** [comment]
@imanghafoori1 thanks for your fast response. I've just watch what you say about the faulty view hahaha I didn't notice at first moment, now It's working.

Thanks.

**Comment by gitllermopalafox** [comment]
I suggest to remove the parameters from `public function data($a, $b)` in the generated example class is part of the above issue and could be tricky to find the error at first moment.

**Comment by imanghafoori1** [comment]
I changed the error message to be more expressive. in v1.9.20
and also the generated files are not faulty ones.

I hope you enjoy my other packages as well.
